# The version of the docker-compose.
version: "3.8"
# Telling docker-compose to build the client and server images and run them in containers.
services:
  client:
    # Telling docker-compose to build the client image using the Dockerfile in the client directory.
    build: ./
    # Giving the container a name.
    container_name: clientapp_c
    # Mapping the port 3000 on the host machine to the port 3000 on the container.
    ports:
      - "4000:4000"
    # Mapping the client directory on the host machine to the /app directory on the container.
    volumes:
      - ./:/app
      - /Users/kencamarador/Downloads/finders/node_modules:/app/node_modules
    # Allows you to run container in detached mode.
    stdin_open: true
    tty: true
  server:
    # Telling docker-compose to build the client image using the Dockerfile in the server directory.
    build: ./backend/
    container_name: serverapp_c
    ports:
      - "4001:4000"
    volumes:
      - ./backend:/app
      - /Users/kencamarador/Downloads/finders/backend/node_modules:/app/node_modules