name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DATABASE: ${{ secrets.DATABASE }}
  PORT: ${{ secrets.PORT }}
  SECRET: ${{ secrets.SECRET }}


  jobs:
  build-and-deploy:
    # This is telling GitHub to run the workflow on the latest version of Ubuntu.
    runs-on: ubuntu-latest

  steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and run tests for the client application
      - name: Install and Test Client
        working-directory: ./
        run: |
          npm install
          

      # Install dependencies, export environment variables to be used by application and run tests for the server application
      - name: Install and Test Server
        working-directory: ./backend
        run: |
          npm install
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_BUCKET_NAM=$AWS_BUCKET_NAME
          export AWS_REGION=$AWS_REGION
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export DATABASE=$DATABASE
          export PORT=$PORT
          export SECRET=$SECRET
          export EMAIL=$EMAIL
          export PASSWORD=$PASSWORD


# Build a Docker image for the client application
      - name: Build Client Docker Image
        working-directory: ./
        # Build image with tag rakeshpotnuru/productivity-app:client
        run: |
          docker build -t kencamarador/finders:client-${{github.run_number}} .

      # Build a Docker image for the server application
      - name: Build Server Docker Image
        working-directory:
          ./backend
          # Build image with tag rakeshpotnuru/productivity-app:server
        run: |
          docker build -t kencamarador/finders:server-${{github.run_number}} .

      # Login to Docker Hub using credentials from repository secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker images to Docker Hub
      - name: Push Docker Images to Docker Hub
        run: |
          docker push kencamarador/finders:client-${{github.run_number}}
          docker push kencamarador/finders:server-${{github.run_number}}
