name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  EMAIL: ${{ secrets.EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DATABASE: ${{ secrets.DATABASE }}
  PORT: ${{ secrets.PORT }}
  SECRET: ${{ secrets.SECRET }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and Test Client
        working-directory: ./
        run: |
          npm install

      - name: Install and Test Server
        working-directory: ./backend
        run: |
          npm install
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_BUCKET_NAM=$AWS_BUCKET_NAME
          export AWS_REGION=$AWS_REGION
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export DATABASE=$DATABASE
          export PORT=$PORT
          export SECRET=$SECRET
          export EMAIL=$EMAIL
          export PASSWORD=$PASSWORD

      - name: Build Client Docker Image
        working-directory: ./
        run: |
          docker build -t kencamarador/finders:client-${{github.run_number}} .

      - name: Build Server Docker Image
        working-directory: ./backend
        run: |
          docker build -t kencamarador/finders:server-${{github.run_number}} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images to Docker Hub
        run: |
          docker push kencamarador/finders:client-${{github.run_number}}
          docker push kencamarador/finders:server-${{github.run_number}}
